### ISSUE TITLE
what is :image-data-fun in org-link-set-parameters?

### ISSUE THREAD

**Issue by jkitchin** [wdavew/org-excalidraw#3]
is this used anywhere? I am not familiar with that link attribute.

**Comment by cpbotha** [comment]
@jkitchin that property seems to add the image previewing capability.

With that code having run, `org-toggle-inline-images` will display `excalidraw:...` images inline.

**Comment by andrewpeck** [comment]
@jkitchin 

I had the same question.. it turns out this parameter comes from org-yt (https://github.com/TobiasZawada/org-yt/blob/56166f48e04d83668f70ed84706b7a4d8b1e5438/org-yt.el) which adds some support for user defined image links. 

This package implicitly depends on that feature for displaying images. This also explains https://github.com/wdavew/org-excalidraw/issues/2

I managed to "fix" this by just copying the `org-image-update-overlay` and `org-display-user-inline-images` functions from org-yt into my user config, and adding the relevant advice: 

```
  (advice-add #'org-display-inline-images :after #'org-display-user-inline-images)
```

**Comment by rafael-unloan** [comment]
Thanks so much @andrewpeck!
